"""
Evidence Generation Agent — Utilities
FIR template generation, risk aggregation, IPC section mapping, PDF generation helpers.
"""

from __future__ import annotations
import hashlib
import os
from datetime import datetime, timezone
from loguru import logger


# ─────────────────────────────────────────────────────────────────────────────
# IPC Section Mapping for common fraud types
# ─────────────────────────────────────────────────────────────────────────────

IPC_SECTIONS = {
    "digital_arrest": ["Section 66C IT Act", "Section 419 IPC", "Section 420 IPC"],
    "upi_fraud": ["Section 420 IPC", "Section 66D IT Act"],
    "banking_fraud": ["Section 420 IPC", "Section 468 IPC", "Section 471 IPC"],
    "whatsapp_fraud": ["Section 66A IT Act", "Section 419 IPC"],
    "voice_phishing": ["Section 419 IPC", "Section 420 IPC", "Section 66C IT Act"],
    "government_impersonation": ["Section 170 IPC", "Section 419 IPC", "Section 420 IPC"],
    "investment_fraud": ["Section 420 IPC", "Section 406 IPC"],
    "counterfeit_currency": ["Section 489A IPC", "Section 489B IPC", "Section 489C IPC"],
    "unknown": ["Section 420 IPC"],
}


def get_ipc_sections(fraud_types: list[str]) -> list[str]:
    sections: set[str] = set()
    for ft in fraud_types:
        sections.update(IPC_SECTIONS.get(ft, IPC_SECTIONS["unknown"]))
    return sorted(sections)


def sha256_file(file_path: str) -> str:
    h = hashlib.sha256()
    try:
        with open(file_path, "rb") as f:
            for chunk in iter(lambda: f.read(8192), b""):
                h.update(chunk)
        return h.hexdigest()
    except Exception:
        return ""


def aggregate_risk_scores(scores: list[float]) -> float:
    """Weighted average — higher scores get more weight."""
    if not scores:
        return 0.0
    scores = sorted([s for s in scores if s is not None], reverse=True)
    # Exponential decay weights
    weights = [1.0 / (2 ** i) for i in range(len(scores))]
    total_w = sum(weights)
    weighted_sum = sum(s * w for s, w in zip(scores, weights))
    return round(weighted_sum / total_w, 4)


def generate_fir_template(
    case_id: str,
    complainant_name: str | None,
    complainant_contact: str | None,
    fraud_type: str,
    risk_score: float,
    entities: dict,
    summary: str,
    ipc_sections: list[str],
    timestamp: datetime,
) -> str:
    """Fill an FIR template with case data."""
    entities_text = "\n".join([
        f"  - Phone Numbers: {', '.join(entities.get('phone_numbers', [])[:5]) or 'None'}",
        f"  - UPI IDs: {', '.join(entities.get('upi_ids', [])[:5]) or 'None'}",
        f"  - URLs: {', '.join(entities.get('urls', [])[:5]) or 'None'}",
        f"  - Amounts: {', '.join(entities.get('amounts', [])[:5]) or 'None'}",
    ])
    ipc_text = ", ".join(ipc_sections) or "Section 420 IPC"

    return f"""
FIRST INFORMATION REPORT (FIR DRAFT)
======================================
Case ID       : {case_id}
Date & Time   : {timestamp.strftime('%Y-%m-%d %H:%M:%S UTC')}
Fraud Type    : {fraud_type.replace('_', ' ').title()}
Risk Level    : {'HIGH' if risk_score >= 0.55 else 'MEDIUM' if risk_score >= 0.30 else 'LOW'}
Risk Score    : {risk_score:.2f}

COMPLAINANT INFORMATION
-----------------------
Name          : {complainant_name or 'Anonymous / Not Provided'}
Contact       : {complainant_contact or 'Not Provided'}

DETAILS OF OFFENCE
------------------
{summary}

ENTITIES INVOLVED
-----------------
{entities_text}

APPLICABLE SECTIONS
-------------------
{ipc_text}

INVESTIGATING OFFICER NOTES
---------------------------
This FIR draft has been auto-generated by SentinelShield AI. 
Please verify all details before filing.

[ ] Victim statement recorded
[ ] Digital evidence preserved
[ ] Accused details verified
[ ] Bank/UPI account flagged for freeze

======================================
[Generated by SentinelShield AI — NOT FOR OFFICIAL USE WITHOUT OFFICER REVIEW]
""".strip()


def save_report_as_text(content: str, case_id: str) -> str | None:
    """Save investigation report as text file. Returns file path."""
    try:
        os.makedirs("reports", exist_ok=True)
        path = os.path.join("reports", f"report_{case_id}_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}.txt")
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        logger.info(f"Report saved: {path}")
        return path
    except Exception as e:
        logger.warning(f"Report save failed: {e}")
        return None


def try_generate_pdf(content: str, case_id: str) -> str | None:
    """Attempt PDF generation via pymupdf. Falls back to text."""
    try:
        import fitz
        os.makedirs("reports", exist_ok=True)
        path = os.path.join("reports", f"report_{case_id}_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}.pdf")
        doc = fitz.open()
        page = doc.new_page()
        rect = fitz.Rect(50, 50, 550, 750)
        page.insert_textbox(rect, content, fontname="courier", fontsize=9, color=(0, 0, 0))
        doc.save(path)
        doc.close()
        logger.info(f"PDF report saved: {path}")
        return path
    except Exception as e:
        logger.warning(f"PDF generation failed ({e}). Falling back to text.")
        return save_report_as_text(content, case_id)
